version: "3.7"

services:
  app:
    image: node:alpine
    working_dir: /home/app
    volumes:
      - .:/home/app
    ports:
      - 8080:8080
    environment:
      - REACT_APP_API_URL=https://hidden-lowlands-01519.herokuapp.com/api
    command: ["yarn", "start"]
